apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-csi
