apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: oauth-secret
  data:
    - secretKey: GoogleOAuth__ClientId
      remoteRef:
        key: google-oauth-client-id
    - secretKey: GoogleOAuth__ClientSecret
      remoteRef:
        key: google-oauth-client-secret
    - secretKey: GoogleOAuth__RedirectUri
      remoteRef:
        key: google-oauth-redirect-uri
    - secretKey: GoogleOAuth__AllowedEmail
      remoteRef:
        key: google-oauth-allowed-email
    - secretKey: Storage__AccountName
      remoteRef:
        key: storage-account-name
