apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.frontend.service.port }}
    protocol: TCP
    targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: frontend
  type: ClusterIP
