apiVersion: v1
kind: ServiceAccount
metadata:
  name: photo-count-worker-sa
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.photoCountWorker.workloadIdentityClientId }}
