apiVersion: v1
kind: Service
metadata:
  labels:
    app: photo-api
  name: photo-api-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.photoApi.service.port }}
    protocol: TCP
    targetPort: {{ .Values.photoApi.service.targetPort }}
  selector:
    app: photo-api
  type: ClusterIP
