apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-worker-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: thumbnail-worker
  template:
    metadata:
      labels:
        app: thumbnail-worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: thumbnail-worker-sa
      containers:
      - image: {{ printf "%s:%s" .Values.worker.image.repository (required "worker.image.tag is required" .Values.worker.image.tag) | quote }}
        name: thumbnail-worker
        env:
        - name: Storage__AccountName
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: Storage__AccountName
        - name: Redis__ConnectionString
          value: {{ .Values.redis.connectionString }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
