apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.web.service.port }}
    protocol: TCP
    targetPort: {{ .Values.web.service.targetPort }}
  selector:
    app: web
  type: ClusterIP
