namespace: longevity

frontend:
  replicaCount: 1
  image:
    repository: longevityacr.azurecr.io/longevity-frontend
    tag: ""
  service:
    port: 80
    targetPort: 80

backend:
  replicaCount: 1
  workloadIdentityClientId: "5e35af52-d86b-4942-992e-b41069dc54db"
  image:
    repository: longevityacr.azurecr.io/longevity-backend
    tag: ""
  service:
    port: 80
    targetPort: 8080
  healthPath: /api/weatherforecast

worker:
  replicaCount: 1
  workloadIdentityClientId: "1d8c230c-695f-4550-a78b-c454a9d93242"
  image:
    repository: longevityacr.azurecr.io/thumbnail-worker
    tag: ""

redis:
  connectionString: redis-svc:6379

postgres:
  storageSize: 1Gi

ingress:
  enabled: true
  className: nginx
  tlsSecretName: web-tls
  host: longevity.eastus2.cloudapp.azure.com
  rateLimit:
    enabled: true
    rps: 120
    burstMultiplier: 3
    connections: 200