namespace: longevity

frontend:
  replicaCount: 1
  image:
    repository: longevityacr.azurecr.io/longevity-frontend
    tag: ""
  service:
    port: 80
    targetPort: 80

backend:
  replicaCount: 1
  workloadIdentityClientId: "5e35af52-d86b-4942-992e-b41069dc54db"
  image:
    repository: longevityacr.azurecr.io/longevity-backend
    tag: ""
  service:
    port: 80
    targetPort: 8080
  healthPath: /api/weatherforecast

ingress:
  enabled: true
  className: nginx
  tlsSecretName: web-tls
  host: longevity.eastus2.cloudapp.azure.com
  rateLimit:
    enabled: true
    rps: 120
    burstMultiplier: 3
    connections: 200