namespace: longevity

web:
  replicaCount: 1
  image:
    repository: longevityacr.azurecr.io/web
    tag: ""
  service:
    port: 80
    targetPort: 80

photoApi:
  replicaCount: 1
  workloadIdentityClientId: "c92417c9-c2ca-4cb5-98ca-dc97de835997"
  image:
    repository: longevityacr.azurecr.io/photo-api
    tag: ""
  service:
    port: 80
    targetPort: 8080
  healthPath: /healthz

worker:
  replicaCount: 1
  workloadIdentityClientId: "1d8c230c-695f-4550-a78b-c454a9d93242"
  image:
    repository: longevityacr.azurecr.io/thumbnail-worker
    tag: ""

photoCountWorker:
  replicaCount: 1
  workloadIdentityClientId: "a082bfcf-e000-4515-bacb-c84c3584578c"
  image:
    repository: longevityacr.azurecr.io/photo-count-worker
    tag: ""
redis:
  connectionString: redis-svc:6379

postgres:
  storageSize: 1Gi

ingress:
  enabled: true
  className: nginx
  tlsSecretName: web-tls
  host: longevity.eastus2.cloudapp.azure.com
  rateLimit:
    enabled: true
    rps: 120
    burstMultiplier: 3
    connections: 200