apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: >-
          {{ .Values.backend.image.repository }}:{{ default .Values.frontend.image.tag .Values.backend.image.tag }}
        name: backend
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
        env:
        - name: ASPNETCORE_URLS
          value: http://+:{{ .Values.backend.service.targetPort }}
        envFrom:
        - secretRef:
            name: oauth-secret
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.healthPath }}
            port: {{ .Values.backend.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.healthPath }}
            port: {{ .Values.backend.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
