apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.backend.service.port }}
    protocol: TCP
    targetPort: {{ .Values.backend.service.targetPort }}
  selector:
    app: backend
  type: ClusterIP
