apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-tls-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.ingress.tlsSecretName }}
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: web-tls-cert
    - secretKey: tls.key
      remoteRef:
        key: web-tls-key
