apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: web-tls-secret-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.ingress.tlsSecretName }}
      type: kubernetes.io/tls
      data:
        - objectName: web-tls-cert
          key: tls.crt
        - objectName: web-tls-key
          key: tls.key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "longevity-kv-001"
    objects: |
      array:
        - |
          objectName: web-tls-cert
          objectType: secret
        - |
          objectName: web-tls-key
          objectType: secret
