ALTER TABLE vocabulary.photos
    ADD COLUMN IF NOT EXISTS word TEXT,
    ADD COLUMN IF NOT EXISTS source TEXT,
    ADD COLUMN IF NOT EXISTS confidence REAL,
    ADD COLUMN IF NOT EXISTS labeled_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS labeled_by TEXT;
