apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      identityId: "338207b5-0abd-46ac-aa59-8b76ffde6171"
      vaultUrl: "https://longevity-kv-001.vault.azure.net/"
