<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="longevity-backend.tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Weather.fs" />
    <Compile Include="Auth.fs" />
    <Compile Include="AuthLogin.fs" />
    <Compile Include="AuthCallback.fs" />
    <Compile Include="PhotoGroups.fs" />
    <Compile Include="Storage.fs" />
    <Compile Include="PhotoHub.fs" />
    <Compile Include="ThumbnailSubscriber.fs" />
    <Compile Include="Config.fs" />
    <Compile Include="Routes.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.18.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
  </ItemGroup>

</Project>
