<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="longevity-backend.tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Weather.fs" />
    <Compile Include="Auth.fs" />
    <Compile Include="AuthLogin.fs" />
    <Compile Include="AuthCallback.fs" />
    <Compile Include="Config.fs" />
    <Compile Include="Routes.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference
      Include="Microsoft.AspNetCore.OpenApi"
      Version="10.0.2" />
  </ItemGroup>

</Project>
