namespace: longevity
replicaCount: 1

image:
  repository: longevityacr.azurecr.io/longevity-frontend
  tag: a9ca507

service:
  port: 80
  targetPort: 80

ingress:
  name: web-ingress
  enabled: true
  className: nginx
  path: /web
  pathType: Prefix
  tlsSecretName: web-tls