namespace: longevity

frontend:
  replicaCount: 1
  image:
    repository: longevityacr.azurecr.io/longevity-frontend
    tag: 5258fe7
  service:
    port: 80
    targetPort: 80

backend:
  replicaCount: 1
  image:
    repository: longevityacr.azurecr.io/longevity-backend
    tag: ""
  service:
    port: 80
    targetPort: 8080
  healthPath: /api/weatherforecast

ingress:
  enabled: true
  className: nginx
  tlsSecretName: web-tls
  host: longevity.eastus2.cloudapp.azure.com